### ISSUE TITLE
gotToMaxPods event after deletion

### ISSUE THREAD

**Issue by yovanoc** [cookie-project/cookietouch#111]

**Comment by Raphael0011** [comment]
ligne 670 ScriptManager.ts :   await sleep(1000);

**Comment by crimson-med** [comment]
@Raphael0011 possible que tu le fasse en Pull Request

**Comment by yovanoc** [comment]
T’inquiète je le ferai j’etais Avec lui en vocal il l’a juste marquer la pour pas l’oublier
