### ISSUE TITLE
Gestion des archimonstres et de la capture

### ISSUE THREAD

**Issue by Suniron** [cookie-project/cookietouch#125]
Demande d'amélioration:

**Archimonstres:**
- Lister les archimonstres rencontrés dans un menu dédié.

**Capture:**
- Possibilité d'équiper une pierre d'âme en fonction du monstre souhaité.
- Procéder à la capture en combat (gestion du sort à x % de vies restantes du dernier monstre en combat par exemple).

**Comment by Raphael0011** [comment]
Je t'avoue que c'est une feature qui est sympas mais y'a beaucoup de chose à faire beaucoup plus important avant ça, peut être un jour ;)
