### ISSUE TITLE
Amélioration des trajets (gestion/script)

### ISSUE THREAD

**Issue by Suniron** [cookie-project/cookietouch#126]
_Demande d'améliorations:_

**Trajets - Script et gestion:**
- Pouvoir renseigner une option ALL à la place d'une POS.
> Ceci peut être utile dans le cas d'une **const bank** afin d’exécuter une fonction stop script sur toutes les maps **fight** par exemple.
- Essayer une direction différente lorsque celle utilisée ne fonctionne pas.
>  Cela pourrait être fait à condition qu'il y en ai plusieurs de renseigné pour une même map.

**Comment by Raphael0011** [comment]
On peut utiliser : currentMapId()
