### ISSUE TITLE
Problème avec la porte de sortie de la banque de Pandala Neutre

### ISSUE THREAD

**Issue by Suniron** [cookie-project/cookietouch#127]
_Rapport de bug:_

**Zone:** Pandala Neutre
**Lieu:** Banque

La CellId de la porte de sortie (CellID: 409) n'est pas reconnue comme une porte. 

![bug1](https://user-images.githubusercontent.com/36677774/44798955-1b480300-abb3-11e8-9e6f-a0f15eeb5895.JPG)
![bug2](https://user-images.githubusercontent.com/36677774/44798956-1b480300-abb3-11e8-945a-0b36ba85a9ce.JPG)
![bug3](https://user-images.githubusercontent.com/36677774/44798957-1b480300-abb3-11e8-8afc-8a29f2fb7109.JPG)

**Comment by crimson-med** [comment]
@Suniron possible d'ajouter une copie du script dans des balise codes

**Comment by Suniron** [comment]
Solution:
Il s'agit d'une erreur dans mon script. 
J'ai oublié les guillemets autour de la CellId.

Fausse alerte donc..
