### ISSUE TITLE
Compteur d'actions

### ISSUE THREAD

**Issue by SwikZy** [cookie-project/cookietouch#150]
Bon bah je vais pas y aller par 4 chemins hein.
Tout simplement mettre un compteur de récoltes/combats tout ça, ça peut aider à voir où on en est de nos limites quotidiennes.

**Comment by xsokaris** [comment]
Il y a déjà un moyen d'afficher ça dans la config des scripts. DISPLAY_FIGHTS_COUNT par exemple, regarde dans la doc

**Comment by SwikZy** [comment]
Ah, pourtant avec aScripter j'active l'option et ça ne l'affiche pas, je pensais juste qu'elle n'était pas ajoutée désolé.
