### ISSUE TITLE
Ajout de motif de notification pushbullet

### ISSUE THREAD

**Issue by Suniron** [cookie-project/cookietouch#152]
_Demande d'évolution:_

**Amélioration du système de notification:**
- Ajout d'une notification lorsqu'un seuil d'argent est gagné.

**Concept:**
L'utilisateur définit un montant au préalable, par exemple 100.000k. Lorsque cette somme a été gagnée par le bot (grâce à la vente d'objets par exemple), une notification est envoyée via le système Pushbullet qui existe aujourd'hui.

**Comment by crimson-med** [comment]
Ceci est deja en partie demandé ici: #166
