### ISSUE TITLE
Onglet DD

### ISSUE THREAD

**Issue by Sectorz** [cookie-project/cookietouch#159]
Bonjours, il faudrais ajouté sur le bot un onglet Dragodindes avec comme action : 

- voire le niveau
- voire l'energie
- voire le % d'exp donné
- voir si on le bot la monte actuellement
- pouvoir changer l'exp donné
et limite mettre une barre d'exp dans personnage de façons a avoir un affichage rapide.

**Comment by crimson-med** [comment]
deja demander sur: #112
