### ISSUE TITLE
Expérience DD

### ISSUE THREAD

**Issue by Altimar21** [cookie-project/cookietouch#179]
**Is your feature request related to a problem? || Votre feature request est-elle reliée à un bug?**

non lié à un bug.

**Describe the solution you'd like || Une description de la solution que vous aimeriez**

Avoir la jauge d’expérience de la DD sur l'onglet de la console. 
Avoir peut être un récapitulatif de l'xp gagné durant le farm dans l'onglet stats en dessous de l'xp gagnée par le perso.

**Describe alternatives you've considered || Une description d'alternatives que vous avez envisagé**

N/A

**Additional context || Plus de contexte**

N/A

**Comment by crimson-med** [comment]
S'integre avec le systeme de DD: #112
