### ISSUE TITLE
Dictionary Mistake 

### ISSUE THREAD

**Issue by Manuriq** [cookie-project/cookietouch#74]
https://github.com/yovanoc/cookietouch/blob/54eccabfc96941cb958e4cc68364b063a8114cb5/src/cookie/utils/Dictionary.ts#L104

`    if (this.mIteratorIndex > this.count() - 1) {`

Fix Gather

**Comment by yovanoc** [comment]
Yes! or `if (this.mIteratorIndex >= this.count()) {`
